=== MikalaiBakhar/IT-AcademyJD1/XML-Scheme/family_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/family-schema"
	xmlns:tns="http://www.example.org/family-schema"
	elementFormDefault="qualified">


	<xs:element name="families">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="family" maxOccurs="unbounded"
					minOccurs="1" type="tns:family_type" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="family_type">
		<xs:sequence>
			<xs:element name="mother" type="tns:mother_type" />
			<xs:element name="father" type="tns:father_type" />
			<xs:element name="children" type="tns:children_type" />
		</xs:sequence>
		<xs:attribute name="adress" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="mother_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="surname" type="xs:string" />
			<xs:element name="maiden-name" type="xs:string" />
			<xs:element name="age" type="xs:int" />
			<xs:element name="hobby">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string" />
						<xs:element name="times-per-week" type="xs:int" />
						<xs:element name="schedule">
							<xs:complexType>
								<xs:choice maxOccurs="unbounded" minOccurs="0">
									<xs:element name="day" type="xs:string" />
									<xs:element name="time" type="xs:string" />
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="father_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="surname" type="xs:string" />
			<xs:element name="age" type="xs:int" />
			<xs:element name="hobby">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string" />
						<xs:element name="times-per-week" type="xs:int" />
						<xs:element name="schedule">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded" minOccurs="0">
									<xs:element name="day" type="xs:string" />
									<xs:element name="time" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="children_type">
		<xs:sequence>
			<xs:element name="child" maxOccurs="unbounded"
				minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="surname" type="xs:string" />
						<xs:element name="age" type="xs:int" />
						<xs:element name="gender" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== MikalaiBakhar/IT-AcademyJD1/XML-Scheme/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<families xmlns="http://www.example.org/family-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/family-schema family_schema.xsd">
	<family adress="CIS,Belarus,Minsk,N186">
		<mother>
			<name>Kate</name>
			<surname>Petrova</surname>
			<maiden-name>Ivanova</maiden-name>
			<age>31</age>
			<hobby>
				<title>Dancing</title>
				<times-per-week>2</times-per-week>
				<schedule>
					<day>monday</day>
					<time>18:00</time>
					<day>friday</day>
					<time>18:00</time>
				</schedule>
			</hobby>
		</mother>
		<father>
			<name>Igor</name>
			<surname>Petrov</surname>
			<age>31</age>
			<hobby>
				<title>Box</title>
				<times-per-week>2</times-per-week>
				<schedule>
					<day>monday</day>
					<time>18:00</time>
					<day>friday</day>
					<time>18:00</time>
				</schedule>
			</hobby>
		</father>
		<children>
			<child>
				<name>Ivan</name>
				<surname>Petrov</surname>
				<age>5</age>
				<gender>male</gender>
			</child>
			<child>
				<name>Olga</name>
				<surname>Petrova</surname>
				<age>6</age>
				<gender>female</gender>
			</child>
		</children>
	</family>
	<family adress="Belarus,Gomel,N1">
		<mother>
			<name>KateTwo</name>
			<surname>PetrovaTwo</surname>
			<maiden-name>IvanovaTwo</maiden-name>
			<age>31</age>
			<hobby>
				<title>DancingTwo</title>
				<times-per-week>2</times-per-week>
				<schedule>
					<day>mondayTwo</day>
					<time>18:00</time>
					<day>fridayTwo</day>
					<time>18:00</time>
				</schedule>
			</hobby>
		</mother>
		<father>
			<name>IgorTwo</name>
			<surname>PetrovTwo</surname>
			<age>31</age>
			<hobby>
				<title>Swimm</title>
				<times-per-week>2</times-per-week>
				<schedule>
					<day>monday</day>
					<time>18:00</time>
					<day>friday</day>
					<time>18:00</time>
				</schedule>
			</hobby>
		</father>
		<children>
			<child>
				<name>IvanTwo</name>
				<surname>PetrovTwo</surname>
				<age>5</age>
				<gender>male</gender>
			</child>
			<child>
				<name>OlgaTwo</name>
				<surname>PetrovaTwo</surname>
				<age>6</age>
				<gender>female</gender>
			</child>
		</children>
	</family>
</families>
